"""Added last_saved_match to account

Revision ID: 17f31445cffe
Revises: 57a2a211d4cd
Create Date: 2026-06-19 16:46:17.752563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f31445cffe'
down_revision: Union[str, Sequence[str], None] = '57a2a211d4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_match_saved', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'last_match_saved')
    # ### end Alembic commands ###
