"""add constraint 2

Revision ID: 25b98caf94f0
Revises: fc71ee102b5c
Create Date: 2026-06-29 02:51:22.405900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b98caf94f0'
down_revision: Union[str, Sequence[str], None] = 'fc71ee102b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_match_player', 'match_players', ['match_id', 'player_tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_match_player', 'match_players', type_='unique')
    # ### end Alembic commands ###
