"""Added game_type field to match

Revision ID: 57a2a211d4cd
Revises: 83dc4dd034a2
Create Date: 2026-06-19 16:10:47.068495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a2a211d4cd'
down_revision: Union[str, Sequence[str], None] = '83dc4dd034a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('game_type', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'game_type')
    # ### end Alembic commands ###
