"""add trophy_change

Revision ID: 82dd0b640273
Revises: 9ae547f19746
Create Date: 2026-06-28 22:02:24.479183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82dd0b640273'
down_revision: Union[str, Sequence[str], None] = '9ae547f19746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_players', sa.Column('trophy_change', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_players', 'trophy_change')
    # ### end Alembic commands ###
