"""Added star_player

Revision ID: 9ae547f19746
Revises: f13f2bc4c053
Create Date: 2026-06-21 01:27:00.488140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae547f19746'
down_revision: Union[str, Sequence[str], None] = 'f13f2bc4c053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('star_player', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'star_player')
    # ### end Alembic commands ###
