"""Added unique_hash

Revision ID: f13f2bc4c053
Revises: 17f31445cffe
Create Date: 2026-06-20 01:02:14.057248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13f2bc4c053'
down_revision: Union[str, Sequence[str], None] = '17f31445cffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('unique_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_matches_unique_hash'), 'matches', ['unique_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_unique_hash'), table_name='matches')
    op.drop_column('matches', 'unique_hash')
    # ### end Alembic commands ###
