"""add constraint

Revision ID: fc71ee102b5c
Revises: 82dd0b640273
Create Date: 2026-06-29 01:15:53.245173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc71ee102b5c'
down_revision: Union[str, Sequence[str], None] = '82dd0b640273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_match_player'), 'match_players', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_match_player'), 'match_players', ['match_id', 'player_tag'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
