"""Added MatchPlayer table

Revision ID: fd16ce2309e7
Revises: 5d8c15f04d0b
Create Date: 2026-06-19 01:47:50.470076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd16ce2309e7'
down_revision: Union[str, Sequence[str], None] = '5d8c15f04d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('player_tag', sa.String(length=32), nullable=False),
    sa.Column('player_nickname', sa.String(length=32), nullable=False),
    sa.Column('brawler', sa.String(length=32), nullable=False),
    sa.Column('trophies', sa.Integer(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_players')
    # ### end Alembic commands ###
